# TCL File Generated by Component Editor 16.0
# Mon May 08 12:45:36 CEST 2017
# DO NOT MODIFY


# 
# avalon_camera "avalon_camera" v1.0
# Javier Lopez Randulfe, Roberto Fernandez Molanes 2017.05.08.12:45:36
# Component for connecting HPS to camera component in FPGA
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module avalon_camera
# 
set_module_property DESCRIPTION "Component for connecting HPS to camera component in FPGA"
set_module_property NAME avalon_camera
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Javier Lopez Randulfe, Roberto Fernandez Molanes"
set_module_property DISPLAY_NAME avalon_camera
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_camera
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_camera.v VERILOG PATH avalon_camera.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter WIDTH STD_LOGIC_VECTOR 320
set_parameter_property WIDTH DEFAULT_VALUE 320
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH WIDTH 18
set_parameter_property WIDTH TYPE STD_LOGIC_VECTOR
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES 0:262143
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter HEIGHT STD_LOGIC_VECTOR 240
set_parameter_property HEIGHT DEFAULT_VALUE 240
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT WIDTH 18
set_parameter_property HEIGHT TYPE STD_LOGIC_VECTOR
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES 0:262143
set_parameter_property HEIGHT HDL_PARAMETER true
add_parameter START_ROW STD_LOGIC_VECTOR 54
set_parameter_property START_ROW DEFAULT_VALUE 54
set_parameter_property START_ROW DISPLAY_NAME START_ROW
set_parameter_property START_ROW WIDTH 18
set_parameter_property START_ROW TYPE STD_LOGIC_VECTOR
set_parameter_property START_ROW UNITS None
set_parameter_property START_ROW ALLOWED_RANGES 0:262143
set_parameter_property START_ROW HDL_PARAMETER true
add_parameter START_COLUMN STD_LOGIC_VECTOR 16
set_parameter_property START_COLUMN DEFAULT_VALUE 16
set_parameter_property START_COLUMN DISPLAY_NAME START_COLUMN
set_parameter_property START_COLUMN WIDTH 18
set_parameter_property START_COLUMN TYPE STD_LOGIC_VECTOR
set_parameter_property START_COLUMN UNITS None
set_parameter_property START_COLUMN ALLOWED_RANGES 0:262143
set_parameter_property START_COLUMN HDL_PARAMETER true
add_parameter ROW_SIZE STD_LOGIC_VECTOR 1439
set_parameter_property ROW_SIZE DEFAULT_VALUE 1439
set_parameter_property ROW_SIZE DISPLAY_NAME ROW_SIZE
set_parameter_property ROW_SIZE WIDTH 18
set_parameter_property ROW_SIZE TYPE STD_LOGIC_VECTOR
set_parameter_property ROW_SIZE UNITS None
set_parameter_property ROW_SIZE ALLOWED_RANGES 0:262143
set_parameter_property ROW_SIZE HDL_PARAMETER true
add_parameter COLUMN_SIZE STD_LOGIC_VECTOR 1919
set_parameter_property COLUMN_SIZE DEFAULT_VALUE 1919
set_parameter_property COLUMN_SIZE DISPLAY_NAME COLUMN_SIZE
set_parameter_property COLUMN_SIZE WIDTH 18
set_parameter_property COLUMN_SIZE TYPE STD_LOGIC_VECTOR
set_parameter_property COLUMN_SIZE UNITS None
set_parameter_property COLUMN_SIZE ALLOWED_RANGES 0:262143
set_parameter_property COLUMN_SIZE HDL_PARAMETER true
add_parameter ROW_MODE STD_LOGIC_VECTOR 2
set_parameter_property ROW_MODE DEFAULT_VALUE 2
set_parameter_property ROW_MODE DISPLAY_NAME ROW_MODE
set_parameter_property ROW_MODE WIDTH 18
set_parameter_property ROW_MODE TYPE STD_LOGIC_VECTOR
set_parameter_property ROW_MODE UNITS None
set_parameter_property ROW_MODE ALLOWED_RANGES 0:262143
set_parameter_property ROW_MODE HDL_PARAMETER true
add_parameter COLUMN_MODE STD_LOGIC_VECTOR 2
set_parameter_property COLUMN_MODE DEFAULT_VALUE 2
set_parameter_property COLUMN_MODE DISPLAY_NAME COLUMN_MODE
set_parameter_property COLUMN_MODE WIDTH 18
set_parameter_property COLUMN_MODE TYPE STD_LOGIC_VECTOR
set_parameter_property COLUMN_MODE UNITS None
set_parameter_property COLUMN_MODE ALLOWED_RANGES 0:262143
set_parameter_property COLUMN_MODE HDL_PARAMETER true
add_parameter EXPOSURE STD_LOGIC_VECTOR 1984
set_parameter_property EXPOSURE DEFAULT_VALUE 1984
set_parameter_property EXPOSURE DISPLAY_NAME EXPOSURE
set_parameter_property EXPOSURE WIDTH 18
set_parameter_property EXPOSURE TYPE STD_LOGIC_VECTOR
set_parameter_property EXPOSURE UNITS None
set_parameter_property EXPOSURE ALLOWED_RANGES 0:262143
set_parameter_property EXPOSURE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_reset_n reset_n Input 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clock
set_interface_property export associatedReset ""
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export avs_export_clk export Output 1
add_interface_port export avs_export_capture_done export Input 1
add_interface_port export avs_export_capture_configure export Output 1
add_interface_port export avs_export_capture_ready export Input 1
add_interface_port export avs_export_capture_select_vga export Output 1
add_interface_port export avs_export_capture_select_output export Output 8
add_interface_port export avs_export_capture_read export Output 1
add_interface_port export avs_export_capture_readdata export Input 32
add_interface_port export avs_export_width export Output 16
add_interface_port export avs_export_height export Output 16
add_interface_port export avs_export_start_row export Output 16
add_interface_port export avs_export_start_column export Output 16
add_interface_port export avs_export_row_size export Output 16
add_interface_port export avs_export_column_size export Output 16
add_interface_port export avs_export_row_mode export Output 16
add_interface_port export avs_export_column_mode export Output 16
add_interface_port export avs_export_exposure export Output 16
add_interface_port export avs_export_capture_start export Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clock_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_s1_address address Input 5
add_interface_port avalon_slave avs_s1_read read Input 1
add_interface_port avalon_slave avs_s1_readdata readdata Output 32
add_interface_port avalon_slave avs_s1_write write Input 1
add_interface_port avalon_slave avs_s1_writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

