# TCL File Generated by Component Editor 16.0
# Wed May 09 13:12:42 CEST 2018
# DO NOT MODIFY


# 
# avalon_image_writer "avalon_image_writer" v1.0
# Roberto Fernandez (robertofem@gmail.com) 2018.05.09.13:12:42
# Saves an image from FPGA into processors memory
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module avalon_image_writer
# 
set_module_property DESCRIPTION "Saves an image from FPGA into processors memory"
set_module_property NAME avalon_image_writer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Roberto Fernandez (robertofem@gmail.com)"
set_module_property DISPLAY_NAME avalon_image_writer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_image_writer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_image_writer.vhd VHDL PATH avalon_image_writer.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter COMPONENT_SIZE INTEGER 8
set_parameter_property COMPONENT_SIZE DEFAULT_VALUE 8
set_parameter_property COMPONENT_SIZE DISPLAY_NAME COMPONENT_SIZE
set_parameter_property COMPONENT_SIZE TYPE INTEGER
set_parameter_property COMPONENT_SIZE UNITS None
set_parameter_property COMPONENT_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property COMPONENT_SIZE HDL_PARAMETER true
add_parameter NUMBER_COMPONENTS INTEGER 1
set_parameter_property NUMBER_COMPONENTS DEFAULT_VALUE 1
set_parameter_property NUMBER_COMPONENTS DISPLAY_NAME NUMBER_COMPONENTS
set_parameter_property NUMBER_COMPONENTS TYPE INTEGER
set_parameter_property NUMBER_COMPONENTS UNITS None
set_parameter_property NUMBER_COMPONENTS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUMBER_COMPONENTS HDL_PARAMETER true
add_parameter PIX_WR INTEGER 4
set_parameter_property PIX_WR DEFAULT_VALUE 4
set_parameter_property PIX_WR DISPLAY_NAME PIX_WR
set_parameter_property PIX_WR TYPE INTEGER
set_parameter_property PIX_WR UNITS None
set_parameter_property PIX_WR ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PIX_WR HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave S_address address Input 4
add_interface_port avalon_slave S_writedata writedata Input 32
add_interface_port avalon_slave S_readdata readdata Output 32
add_interface_port avalon_slave S_write write Input 1
add_interface_port avalon_slave S_read read Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master M_address address Output 32
add_interface_port avalon_master M_write write Output 1
add_interface_port avalon_master M_byteenable byteenable Output pix_wr*number_components*component_size/8
add_interface_port avalon_master M_writedata writedata Output pix_wr*number_components*component_size
add_interface_port avalon_master M_waitrequest waitrequest Input 1
add_interface_port avalon_master M_burstcount burstcount Output 7


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end data_valid data_valid Input 1
add_interface_port conduit_end input_data input_data Input number_components*component_size
add_interface_port conduit_end img_width img_width Input 16
add_interface_port conduit_end img_height img_height Input 16


# 
# connection point stream_reset_sink
# 
add_interface stream_reset_sink reset end
set_interface_property stream_reset_sink associatedClock clock
set_interface_property stream_reset_sink synchronousEdges DEASSERT
set_interface_property stream_reset_sink ENABLED true
set_interface_property stream_reset_sink EXPORT_OF ""
set_interface_property stream_reset_sink PORT_NAME_MAP ""
set_interface_property stream_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property stream_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port stream_reset_sink stream_reset_n reset_n Input 1

