# TCL File Generated by Component Editor 16.0
# Thu May 25 21:29:08 CEST 2017
# DO NOT MODIFY


# 
# avalon_write_bridge "avalon_write_bridge" v1.0
#  2017.05.25.21:29:08
# 
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module avalon_write_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_write_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_write_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_write_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_write_bridge.vhd VHDL PATH avalon_write_bridge.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_SIZE INTEGER 32
set_parameter_property DATA_SIZE DEFAULT_VALUE 32
set_parameter_property DATA_SIZE DISPLAY_NAME DATA_SIZE
set_parameter_property DATA_SIZE TYPE INTEGER
set_parameter_property DATA_SIZE UNITS None
set_parameter_property DATA_SIZE HDL_PARAMETER true
add_parameter ADDRESS_SIZE INTEGER 32
set_parameter_property ADDRESS_SIZE DEFAULT_VALUE 32
set_parameter_property ADDRESS_SIZE DISPLAY_NAME ADDRESS_SIZE
set_parameter_property ADDRESS_SIZE TYPE INTEGER
set_parameter_property ADDRESS_SIZE UNITS None
set_parameter_property ADDRESS_SIZE HDL_PARAMETER true
add_parameter BURSCOUNT_SIZE INTEGER 7
set_parameter_property BURSCOUNT_SIZE DEFAULT_VALUE 7
set_parameter_property BURSCOUNT_SIZE DISPLAY_NAME BURSCOUNT_SIZE
set_parameter_property BURSCOUNT_SIZE TYPE INTEGER
set_parameter_property BURSCOUNT_SIZE UNITS None
set_parameter_property BURSCOUNT_SIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_write_address address Input address_size
add_interface_port avalon_slave avs_write_write write Input 1
add_interface_port avalon_slave avs_write_byteenable byteenable Input data_size/8
add_interface_port avalon_slave avs_write_writedata writedata Input data_size
add_interface_port avalon_slave avs_write_waitrequest waitrequest Output 1
add_interface_port avalon_slave avs_write_burstcount burstcount Input burscount_size
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avm_write_address address Output address_size
add_interface_port avalon_master avm_write_write write Output 1
add_interface_port avalon_master avm_write_byteenable byteenable Output data_size/8
add_interface_port avalon_master avm_write_writedata writedata Output data_size
add_interface_port avalon_master avm_write_waitrequest waitrequest Input 1
add_interface_port avalon_master avm_write_burstcount burstcount Output burscount_size

